# docker-compose.yml
version: '3'
services:
  gotrue: # Signup enabled, autoconfirm off
    image: supabase/gotrue:latest
    ports:
      - '9999:9999'
    environment:
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: '/verify'
      GOTRUE_JWT_SECRET: '37c304f8-51aa-419a-a1af-06154e63707a'
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DB_DRIVER: postgres
      DB_NAMESPACE: auth
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9999
      GOTRUE_DISABLE_SIGNUP: 'false'
      API_EXTERNAL_URL: http://localhost:9999
      GOTRUE_SITE_URL: http://localhost:9999
      GOTRUE_URI_ALLOW_LIST: https://supabase.io/docs
      GOTRUE_MAILER_AUTOCONFIRM: 'false'
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: 'true'
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: 53566906701-bmhc1ndue7hild39575gkpimhs06b7ds.apps.googleusercontent.com
      GOTRUE_EXTERNAL_GOOGLE_SECRET: Sm3s8RE85rDcS36iMy8YjrpC
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: http://localhost:9999/callback
      GOTRUE_SMTP_HOST: mail
      GOTRUE_SMTP_PORT: 2500
      GOTRUE_SMTP_USER: GOTRUE_SMTP_USER
      GOTRUE_SMTP_PASS: GOTRUE_SMTP_PASS
      GOTRUE_SMTP_ADMIN_EMAIL: admin@email.com
      GOTRUE_MAILER_SUBJECTS_CONFIRMATION: 'Please confirm'
      GOTRUE_EXTERNAL_PHONE_ENABLED: 'true'
      GOTRUE_SMS_PROVIDER: "twilio"
      GOTRUE_SMS_TWILIO_ACCOUNT_SID: "${GOTRUE_SMS_TWILIO_ACCOUNT_SID}"
      GOTRUE_SMS_TWILIO_AUTH_TOKEN: "${GOTRUE_SMS_TWILIO_AUTH_TOKEN}"
      GOTRUE_SMS_TWILIO_MESSAGE_SERVICE_SID: "${GOTRUE_SMS_TWILIO_MESSAGE_SERVICE_SID}"
      GOTRUE_SMS_AUTOCONFIRM: 'false'
    depends_on:
      - db
    restart: on-failure
  autoconfirm: # Signup enabled, autoconfirm on
    image: supabase/gotrue:latest
    ports:
      - '9998:9998'
    environment:
      GOTRUE_JWT_SECRET: '37c304f8-51aa-419a-a1af-06154e63707a'
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DB_DRIVER: postgres
      DB_NAMESPACE: auth
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9998
      GOTRUE_DISABLE_SIGNUP: 'false'
      API_EXTERNAL_URL: http://localhost:9998
      GOTRUE_SITE_URL: http://localhost:9998
      GOTRUE_MAILER_AUTOCONFIRM: 'true'
      GOTRUE_SMS_AUTOCONFIRM: 'true'
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
      GOTRUE_EXTERNAL_PHONE_ENABLED: 'true'
      GOTRUE_SMS_AUTOCONFIRM: 'true'
      GOTRUE_SMTP_HOST: mail
      GOTRUE_SMTP_PORT: 2500
      GOTRUE_SMTP_USER: GOTRUE_SMTP_USER
      GOTRUE_SMTP_PASS: GOTRUE_SMTP_PASS
      GOTRUE_SMTP_ADMIN_EMAIL: admin@email.com
    depends_on:
      - db
    restart: on-failure
  disabled: # Signup disabled
    image: supabase/gotrue:latest
    ports:
      - '9997:9997'
    environment:
      GOTRUE_JWT_SECRET: '37c304f8-51aa-419a-a1af-06154e63707a'
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DB_DRIVER: postgres
      DB_NAMESPACE: auth
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9997
      GOTRUE_DISABLE_SIGNUP: 'true'
      API_EXTERNAL_URL: http://localhost:9997
      GOTRUE_SITE_URL: http://localhost:9997
      GOTRUE_MAILER_AUTOCONFIRM: 'false'
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: super-secret-operator-token
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
      GOTRUE_EXTERNAL_PHONE_ENABLED: 'false'
      GOTRUE_EXTERNAL_EMAIL_ENABLED: 'false'
      GOTRUE_SMTP_HOST: mail
      GOTRUE_SMTP_PORT: 2500
      GOTRUE_SMTP_USER: GOTRUE_SMTP_USER
      GOTRUE_SMTP_PASS: GOTRUE_SMTP_PASS
      GOTRUE_SMTP_ADMIN_EMAIL: admin@email.com
    depends_on:
      - db
    restart: on-failure
  mail:
    image: phamhieu/inbucket:latest
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3
  db:
    image: supabase/postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
