name: Check pull requests

on:
  push:
    branches-ignore: # Run the checks on all branches but the protected ones
      - master
      - release/*

  pull_request_target:
    branches:
      - master
      - release/*
    types:
      - opened
      - edited
      - reopened
      - ready_for_review

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - if: ${{ github.event_name == 'pull_request_target' }}
        run: |
          set -ex

          node .github/workflows/conventional-commits-lint.js pr <<EOF
          ${{ toJSON(github.event) }}
          EOF

      - if: ${{ github.event_name == 'push' }}
        run: |
          set -ex

          node .github/workflows/conventional-commits-lint.js push <<EOF
          ${{ toJSON(github.event) }}
          EOF
